RAZORPAY_KEY_ID = "rzp_test_Sw2nbZyIHRard2"
RAZORPAY_KEY_SECRET = "lFE8YAHdIdGbAd4ejBS4bnAt"

SUPABASE_URL = "https://ptaeclaqabmjcnicydmx.supabase.co"
SUPABASE_KEY = "sb_publishable_A_fbYWs-QbxX_LWQW5mJyw_3B7Ci9Jg"